In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.special as special
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.read_csv('listings_50_outliers_oslo.csv')
df.head(20)

Unnamed: 0 last_scraped      host_name  host_since    host_location  \
0            0    9/28/2024  Lars Kristian   7/19/2014     Oslo, Norway   
1            1    9/28/2024        Cecilie    8/1/2010     Oslo, Norway   
2            2    9/28/2024         Reidun   1/30/2011     Oslo, Norway   
3            3    9/28/2024        Melissa   10/1/2010     Oslo, Norway   
4            4    9/28/2024        Melissa   10/1/2010     Oslo, Norway   
5            5    9/28/2024         Henrik   6/18/2011     Oslo, Norway   
6            6    9/28/2024            Jon    7/7/2011     Oslo, Norway   
7            7    9/28/2024      Christina   4/26/2010     Oslo, Norway   
8            8    9/28/2024   Kåre & Truls  10/29/2011     Oslo, Norway   
9            9    9/28/2024          Espen    7/8/2011  Berlin, Germany   
10          10    9/28/2024          Bente  10/23/2011     Oslo, Norway   
11          11    9/28/2024    Peter Piotr   1/16/2012     Oslo, Norway   
12          12    9/28/2024          Hanne   3/22/2012     Oslo, Norway   
13          13    9/28/2024         Marius   3/28/2012     Oslo, Norway   
14          14    9/28/2024       Volkolas   5/15/2012     Oslo, Norway   
15          15    9/28/2024          Jarle   5/28/2012     Oslo, Norway   
16          16    9/28/2024           Bent   7/12/2012     Oslo, Norway   
17          17    9/28/2024    Elin Killie  10/10/2011     Oslo, Norway   
18          18    9/28/2024         Merete    8/5/2012     Oslo, Norway   
19          19    9/28/2024        Kjersti   5/21/2012     Oslo, Norway   

    host_response_time host_response_rate host_acceptance_rate  \
0         within a day               100%                 100%   
1       within an hour               100%                 100%   
2         within a day               100%                  71%   
3       within an hour               100%                  96%   
4       within an hour               100%                  96%   
5       within an hour               100%                 100%   
6       within an hour               100%                 100%   
7         within a day               100%                 100%   
8   within a few hours               100%                  77%   
9         within a day               100%                  63%   
10      within an hour               100%                 100%   
11      within an hour               100%                  95%   
12      within an hour               100%                  78%   
13      within an hour               100%                   0%   
14        within a day               100%                   0%   
15  within a few hours               100%                  93%   
16      within an hour               100%                  33%   
17        within a day               100%                  67%   
18        within a day               100%                 100%   
19        within a day               100%                  33%   

   host_is_superhost host_has_profile_pic  ... number_of_reviews_l30d  \
0                  f                    t  ...                    0.0   
1                  f                    t  ...                    0.0   
2                  f                    t  ...                    0.0   
3                  t                    t  ...                    0.0   
4                  t                    t  ...                    0.0   
5                  f                    t  ...                    0.0   
6                  f                    t  ...                    2.0   
7                  f                    t  ...                    0.0   
8                  t                    t  ...                    0.3   
9                  t                    t  ...                    1.0   
10                 f                    t  ...                    0.3   
11                 t                    t  ...                    0.0   
12                 f                    t  ...                    0.0   
13                 

In [7]:
#df = df.drop(columns=['Unnamed: 0'])
df

last_scraped         host_name host_since host_location  \
0        9/28/2024     Lars Kristian  7/19/2014  Oslo, Norway   
1        9/28/2024           Cecilie   8/1/2010  Oslo, Norway   
2        9/28/2024            Reidun  1/30/2011  Oslo, Norway   
3        9/28/2024           Melissa  10/1/2010  Oslo, Norway   
4        9/28/2024           Melissa  10/1/2010  Oslo, Norway   
...            ...               ...        ...           ...   
10447    9/28/2024             Stian  9/12/2024            10   
10448    9/28/2024             Johan  10/9/2014  Oslo, Norway   
10449    9/28/2024  Jonas Kristoffer  9/26/2024            10   
10450    9/28/2024       Lina Hovden  6/24/2015  Oslo, Norway   
10451    9/28/2024         Madeleine   4/4/2018            10   

      host_response_time host_response_rate host_acceptance_rate  \
0           within a day               100%                 100%   
1         within an hour               100%                 100%   
2           within a day               100%                  71%   
3         within an hour               100%                  96%   
4         within an hour               100%                  96%   
...                  ...                ...                  ...   
10447       within a day               100%                  50%   
10448       within a day               100%                  50%   
10449       within a day               100%                  50%   
10450       within a day               100%                  50%   
10451       within a day               100%                  50%   

      host_is_superhost host_has_profile_pic host_identity_verified  ...  \
0                     f                    t                      t  ...   
1                     f                    t                      t  ...   
2                     f                    t                      t  ...   
3                     t                    t                      t  ...   
4                     t                    t                      t  ...   
...                 ...                  ...                    ...  ...   
10447                 f                    t                      f  ...   
10448                 f                    t                      t  ...   
10449                 f                    f                      t  ...   
10450                 f                    t                      f  ...   
10451                 f                    t                      f  ...   

      number_of_reviews_l30d review_scores_rating review_scores_accuracy  \
0                        0.0                 5.00                   5.00   
1                        0.0                 4.91                   4.96   
2                        0.0                 4.75                   4.69   
3                        0.0                 4.77                   4.78   
4                        0.0                 4.82                   4.85   
...                      ...                  ...                    ...   
10447                    0.0                 4.90                   4.90   
10448                    0.0                 4.90                   4.90   
10449                    0.0                 4.90                   4.90   
10450                    0.0                 4.90                   4.90   
10451                    0.0                 4.90                   4.90   

       review_scores_cleanliness review_scores_checkin review_scores_location  \
0                           4.00                  5.00                   5.00   
1                           4.98                  4.92                   4.96   
2                           4.78                  4.98                   4.71   
3                           4.58                  4.74                   4.49   
4                           4.72                  4.85                   4.60   
...                          ...                   ...                    ...   
10447          

In [8]:
df=df.fillna(method='bfill')
df=df.fillna(method='ffill')

C:\Users\hegbj\AppData\Local\Temp\ipykernel_19732\1110552620.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='bfill')
C:\Users\hegbj\AppData\Local\Temp\ipykernel_19732\1110552620.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')


In [10]:
Var_Indep = df[['price', 'reviews_per_month', 'minimum_nights']]
Var_Dep = df['host_is_superhost']


In [24]:
unic=df['price'].unique()
unic

array([   0., 3400.,  586., ...,  874.,  492.,  738.])

In [11]:
X=Var_Indep
y=Var_Dep

In [12]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=None)

In [13]:
escalar=StandardScaler()

In [14]:
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

In [16]:
algoritmo.fit(X_train,y_train)

LogisticRegression()

In [17]:
y_pred=algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [18]:
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test,y_pred)
print('matriz de confusion')
print(matriz)

matriz de confusion
[[2573    0]
 [ 563    0]]


In [21]:
from sklearn.metrics import precision_score
precision=precision_score(y_test,y_pred, average='binary', pos_label='f')
print('precision')
print(precision)

precision
0.8204719387755102


In [22]:
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test,y_pred)
print('exactitud del modelo')
print(exactitud)

exactitud del modelo
0.8204719387755102


In [26]:
Var_Indep2 = df[['accommodates', 'bathrooms', 'bedrooms', 'beds']]
Var_Dep2 = df['instant_bookable']


In [28]:
X2=Var_Indep2
y2=Var_Dep2

In [29]:
x_train2, x_test2, y_train2, y_test2 = train_test_split( X2, y2, test_size=0.3, random_state=None)

In [30]:
escalar2=StandardScaler()

In [31]:
X_train2=escalar2.fit_transform(x_train2)
X_test2=escalar2.transform(x_test2)

In [32]:
from sklearn.linear_model import LogisticRegression
algoritmo2=LogisticRegression()
    

In [33]:
algoritmo2.fit(X_train2,y_train2)

LogisticRegression()

In [34]:
y_pred2=algoritmo2.predict(X_test2)
y_pred2

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [35]:
matriz2=confusion_matrix(y_test2,y_pred2)
print('matriz de confusion')
print(matriz2)

matriz de confusion
[[2872    0]
 [ 264    0]]


In [41]:
precision2=precision_score(y_test2,y_pred2, average='binary', pos_label='f')
print('precision')
print(precision2)


precision
0.9158163265306123


In [37]:
exactitud2=accuracy_score(y_test2,y_pred2)
print('exactitud del modelo')
print(exactitud2)

exactitud del modelo
0.9158163265306123


In [39]:
from sklearn.metrics import recall_score
sensibilidad2=recall_score(y_test2,y_pred2, average='binary', pos_label='f')
print('sensibilidad')
print(sensibilidad2)

sensibilidad
1.0


In [43]:
Var_Indep3 = df[['price', 'number_of_reviews']]
Var_Dep3 = df['host_identity_verified']


In [44]:
Var_Indep4 = df[['minimum_nights', 'reviews_per_month', 'beds']]
Var_Dep4 = df['host_is_superhost']


In [45]:
Var_Indep5 = df[['price', 'accommodates', 'bathrooms', 'number_of_reviews']]
Var_Dep5 = df['instant_bookable']


In [46]:
Var_Indep6 = df[['bedrooms', 'beds', 'reviews_per_month']]
Var_Dep6 = df['host_identity_verified']

In [48]:
Var_Indep7 = df[['price', 'minimum_nights', 'number_of_reviews']]
Var_Dep7 = df['host_is_superhost']


In [49]:
Var_Indep8 = df[['accommodates', 'bathrooms', 'bedrooms']]
Var_Dep8 = df['instant_bookable']

In [51]:
Var_Indep9 = df[['price', 'reviews_per_month', 'beds']]
Var_Dep9 = df['host_identity_verified']

In [52]:
X3=Var_Indep3
y3=Var_Dep3

In [53]:
X4=Var_Indep4
y4=Var_Dep4

In [55]:
X5=Var_Indep5
y5=Var_Dep5

In [56]:
X6=Var_Indep6
y6=Var_Dep6

In [57]:
X7=Var_Indep7
y7=Var_Dep7

In [58]:
X8=Var_Indep8
y8=Var_Dep8

In [59]:
X9=Var_Indep9
y9=Var_Dep9

In [60]:
X_train3, X_test3, y_train3, y_test3 = train_test_split( X3, y3, test_size=0.3, random_state=None)
escalar3=StandardScaler()

In [61]:
X_train4, X_test4, y_train4, y_test4 = train_test_split( X4, y4, test_size=0.3, random_state=None)
escalar4=StandardScaler()

In [62]:
X_train5, X_test5, y_train5, y_test5 = train_test_split( X5, y5, test_size=0.3, random_state=None)
escalar5=StandardScaler()

In [63]:
x_train6, x_test6, y_train6, y_test6 = train_test_split( X6, y6, test_size=0.3, random_state=None)
escalar6=StandardScaler()

In [64]:
x_train7, x_test7, y_train7, y_test7 = train_test_split( X7, y7, test_size=0.3, random_state=None)
escalar7=StandardScaler()

In [65]:
x_train8, x_test8, y_train8, y_test8 = train_test_split( X8, y8, test_size=0.3, random_state=None)
escalar8=StandardScaler()

In [66]:
x_train9, x_test9, y_train9, y_test9 = train_test_split( X9, y9, test_size=0.3, random_state=None)
escalar9=StandardScaler()

In [67]:
algoritmo3=LogisticRegression()
algoritmo4=LogisticRegression()
algoritmo5=LogisticRegression()
algoritmo6=LogisticRegression()
algoritmo7=LogisticRegression()
algoritmo8=LogisticRegression()
algoritmo9=LogisticRegression()

In [68]:
algoritmo3.fit(X_train3,y_train3)
y_pred3=algoritmo3.predict(X_test3)


In [69]:
algoritmo4.fit(X_train4,y_train4)
y_pred4=algoritmo4.predict(X_test4)

In [70]:
algoritmo5.fit(X_train5,y_train5)
y_pred5=algoritmo5.predict(X_test5)

In [71]:
algoritmo6.fit(x_train6,y_train6)
y_pred6=algoritmo6.predict(x_test6)

In [72]:
algoritmo7.fit(x_train7,y_train7)
y_pred7=algoritmo7.predict(x_test7)

In [73]:
algoritmo8.fit(x_train8,y_train8)
y_pred8=algoritmo8.predict(x_test8)

In [74]:
algoritmo9.fit(x_train9,y_train9)
y_pred9=algoritmo9.predict(x_test9)

In [75]:
from sklearn.metrics import confusion_matrix
matriz3=confusion_matrix(y_test3,y_pred3)
print('matriz de confusion')
print(matriz3)

matriz de confusion
[[   0  635]
 [   0 2501]]


In [76]:
from sklearn.metrics import confusion_matrix
matriz4=confusion_matrix(y_test4,y_pred4)
print('matriz de confusion')
print(matriz4)

matriz de confusion
[[2563    0]
 [ 573    0]]


In [77]:
from sklearn.metrics import confusion_matrix
matriz5=confusion_matrix(y_test5,y_pred5)
print('matriz de confusion')
print(matriz5)

matriz de confusion
[[2861    0]
 [ 275    0]]


In [78]:
from sklearn.metrics import confusion_matrix
matriz6=confusion_matrix(y_test6,y_pred6)
print('matriz de confusion')
print(matriz6)

matriz de confusion
[[   0  632]
 [   0 2504]]


In [79]:
from sklearn.metrics import confusion_matrix
matriz7=confusion_matrix(y_test7,y_pred7)
print('matriz de confusion')
print(matriz7)

matriz de confusion
[[2474   89]
 [ 490   83]]


In [80]:
from sklearn.metrics import confusion_matrix
matriz8=confusion_matrix(y_test8,y_pred8)
print('matriz de confusion')
print(matriz8)

matriz de confusion
[[2869    0]
 [ 267    0]]


In [81]:
from sklearn.metrics import confusion_matrix
matriz9=confusion_matrix(y_test9,y_pred9)
print('matriz de confusion')
print(matriz9)

matriz de confusion
[[   0  599]
 [   0 2537]]


In [82]:
from sklearn.metrics import precision_score
precision3=precision_score(y_test3,y_pred3, average='binary', pos_label='t')
print('precision')
print(precision3)

precision
0.7975127551020408


In [84]:
from sklearn.metrics import precision_score
precision4=precision_score(y_test4,y_pred4, average='binary', pos_label='f')
print('precision')
print(precision4)

precision
0.8172831632653061


In [86]:
from sklearn.metrics import precision_score
precision5=precision_score(y_test5,y_pred5, average='binary', pos_label='f')
print('precision')
print(precision5)

precision
0.9123086734693877


In [87]:
from sklearn.metrics import precision_score
precision6=precision_score(y_test6,y_pred6, average='binary', pos_label='t')
print('precision')
print(precision6)

precision
0.798469387755102


In [89]:
from sklearn.metrics import precision_score
precision7=precision_score(y_test7,y_pred7, average='binary', pos_label='t')
print('precision')
print(precision7)

precision
0.48255813953488375


In [91]:
from sklearn.metrics import precision_score
precision8=precision_score(y_test8,y_pred8, average='binary', pos_label='f')
print('precision')
print(precision8)

precision
0.9148596938775511


In [92]:
from sklearn.metrics import precision_score
precision9=precision_score(y_test9,y_pred9, average='binary', pos_label='t')
print('precision')
print(precision9)

precision
0.8089923469387755


In [93]:
from sklearn.metrics import accuracy_score
exactitud3=accuracy_score(y_test3,y_pred3)
print('exactitud del modelo')
print(exactitud3)

exactitud del modelo
0.7975127551020408


In [94]:
from sklearn.metrics import accuracy_score
exactitud4=accuracy_score(y_test4,y_pred4)
print('exactitud del modelo')
print(exactitud4)

exactitud del modelo
0.8172831632653061


In [95]:
from sklearn.metrics import accuracy_score
exactitud5=accuracy_score(y_test5,y_pred5) 
print('exactitud del modelo')
print(exactitud5)


exactitud del modelo
0.9123086734693877


In [96]:
from sklearn.metrics import accuracy_score
exactitud6=accuracy_score(y_test6,y_pred6)
print('exactitud del modelo')
print(exactitud6)

exactitud del modelo
0.798469387755102


In [97]:
from sklearn.metrics import accuracy_score
exactitud7=accuracy_score(y_test7,y_pred7)
print('exactitud del modelo')
print(exactitud7)
    

exactitud del modelo
0.8153698979591837


In [98]:
from sklearn.metrics import accuracy_score
exactitud8=accuracy_score(y_test8,y_pred8)
print('exactitud del modelo')
print(exactitud8)

exactitud del modelo
0.9148596938775511


In [99]:
from sklearn.metrics import accuracy_score
exactitud9=accuracy_score(y_test9,y_pred9)
print('exactitud del modelo')
print(exactitud9)

exactitud del modelo
0.8089923469387755


In [103]:
from sklearn.metrics import recall_score
sensibilidad3=recall_score(y_test3,y_pred3, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad3)


sensibilidad
1.0


In [104]:
from sklearn.metrics import recall_score
sensibilidad4=recall_score(y_test4,y_pred4, average='binary', pos_label='f')
print('sensibilidad')
print(sensibilidad4)

sensibilidad
1.0


In [105]:
from sklearn.metrics import recall_score
sensibilidad5=recall_score(y_test5,y_pred5, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad5)

sensibilidad
0.0


In [106]:
from sklearn.metrics import recall_score
sensibilidad6=recall_score(y_test6,y_pred6, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad6)

sensibilidad
1.0


In [107]:
from sklearn.metrics import recall_score
sensibilidad7=recall_score(y_test7,y_pred7, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad7)

sensibilidad
0.14485165794066318


In [110]:
from sklearn.metrics import recall_score
sensibilidad8=recall_score(y_test8,y_pred8, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad8)

sensibilidad
0.0


In [109]:
from sklearn.metrics import recall_score
sensibilidad9=recall_score(y_test9,y_pred9, average='binary', pos_label='t')
print('sensibilidad')
print(sensibilidad9)

sensibilidad
1.0
