In [215]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [216]:
#cargar archivo desde seaborn 
df=pd.read_csv('spain_menorca_procesado_outliers (2) (1).csv')
df.head(5)

Unnamed: 0 last_scraped host_name  host_since      host_location  \
0           0   2024-09-30   Manuela  2010-08-06  Sant Lluís, Spain   
1           1   2024-09-30   Yolanda  2011-04-26   Barcelona, Spain   
2           2   2024-09-30   Natalia  2010-12-07      Madrid, Spain   
3           3   2024-09-30   Natalia  2010-12-07      Madrid, Spain   
4           4   2024-09-30    Emilio  2012-02-12     Torrent, Spain   

   host_response_time host_response_rate host_acceptance_rate  \
0      within an hour               100%                 100%   
1  within a few hours               100%                  94%   
2  a few days or more                20%                   0%   
3  a few days or more                20%                   0%   
4      within an hour               100%                  83%   

  host_is_superhost host_has_profile_pic  ... number_of_reviews_l30d  \
0                 t                    t  ...                    0.0   
1                 f                    t  ...                    2.0   
2                 f                    t  ...                    0.0   
3                 f                    t  ...                    0.0   
4                 t                    t  ...                    2.0   

  review_scores_rating review_scores_accuracy review_scores_cleanliness  \
0                 4.65                   4.76                      4.62   
1                 4.69                   4.77                      4.68   
2                 4.55                   4.45                      4.27   
3                 4.83                   4.79                      4.54   
4                 4.99                   4.96                      4.99   

  review_scores_checkin review_scores_location  \
0                  4.75                   4.75   
1                  4.75                   4.77   
2                  4.50                   4.50   
3                  4.65                   4.70   
4                  4.95                   4.94   

  calculated_host_listings_count_entire_homes  \
0                                         3.0   
1                                         1.0   
2                                         3.0   
3                                         3.0   
4                                         1.0   

  calculated_host_listings_count_private_rooms  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                         0.0              0.14  
1                                         0.0              0.40  
2                                         0.0              0.10  
3                                         0.0              0.16  
4                                         0.0              0.53  

[5 rows x 51 columns]

In [217]:
#eliminamos la columna unnamed 
df= df.drop(['Unnamed: 0'], axis=1)
df.head(5)

last_scraped host_name  host_since      host_location  host_response_time  \
0   2024-09-30   Manuela  2010-08-06  Sant Lluís, Spain      within an hour   
1   2024-09-30   Yolanda  2011-04-26   Barcelona, Spain  within a few hours   
2   2024-09-30   Natalia  2010-12-07      Madrid, Spain  a few days or more   
3   2024-09-30   Natalia  2010-12-07      Madrid, Spain  a few days or more   
4   2024-09-30    Emilio  2012-02-12     Torrent, Spain      within an hour   

  host_response_rate host_acceptance_rate host_is_superhost  \
0               100%                 100%                 t   
1               100%                  94%                 f   
2                20%                   0%                 f   
3                20%                   0%                 f   
4               100%                  83%                 t   

  host_has_profile_pic host_identity_verified  ... number_of_reviews_l30d  \
0                    t                      t  ...                    0.0   
1                    t                      t  ...                    2.0   
2                    t                      t  ...                    0.0   
3                    t                      t  ...                    0.0   
4                    t                      t  ...                    2.0   

  review_scores_rating review_scores_accuracy review_scores_cleanliness  \
0                 4.65                   4.76                      4.62   
1                 4.69                   4.77                      4.68   
2                 4.55                   4.45                      4.27   
3                 4.83                   4.79                      4.54   
4                 4.99                   4.96                      4.99   

  review_scores_checkin review_scores_location  \
0                  4.75                   4.75   
1                  4.75                   4.77   
2                  4.50                   4.50   
3                  4.65                   4.70   
4                  4.95                   4.94   

  calculated_host_listings_count_entire_homes  \
0                                         3.0   
1                                         1.0   
2                                         3.0   
3                                         3.0   
4                                         1.0   

  calculated_host_listings_count_private_rooms  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                         0.0              0.14  
1                                         0.0              0.40  
2                                         0.0              0.10  
3                                         0.0              0.16  
4                                         0.0              0.53  

[5 rows x 50 columns]

In [ ]:
#cargar archivo csv desde seaboarn
#df=sns.load_dataset(name='titanic')
#df.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [218]:
# Relleno de valores nulos 

df = df.fillna(method="bfill")
df = df.fillna(method="ffill")

C:\Users\ben31\AppData\Local\Temp\ipykernel_696\2761572045.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="bfill")
C:\Users\ben31\AppData\Local\Temp\ipykernel_696\2761572045.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="ffill")


In [219]:
# Asegúrate de que tienes un DataFrame llamado 'df'
print(df.columns)

Index(['last_scraped', 'host_name', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_has_profile_pic', 'host_identity_verified',
       'property_type', 'room_type', 'bathrooms_text', 'price',
       'has_availability', 'calendar_last_scraped', 'first_review',
       'last_review', 'license', 'instant_bookable', 'id', 'host_id',
       'host_listings_count', 'host_total_listings_count', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30',
       'availability_90', 'number_of_reviews', 'number_of_reviews_ltm',
       'number_of_reviews_l30d', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_

In [ ]:
#f1=df

In [220]:
# Imprimir las columnas que son de tipo numérico
numeric_columns = df.select_dtypes(include=['number']).columns
print(numeric_columns)

Index(['id', 'host_id', 'host_listings_count', 'host_total_listings_count',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'minimum_nights',
       'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'availability_30',
       'availability_90', 'number_of_reviews', 'number_of_reviews_ltm',
       'number_of_reviews_l30d', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_location',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')


In [221]:
df['price'] = df['price'].astype(str).str.replace(r'[\$,]', '', regex=True)
df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0)

In [222]:
print(df['price'].head())

0     408.0
1      64.0
2     567.0
3    1125.0
4      69.0
Name: price, dtype: float64


In [95]:
#convertimos string a tipos numéricos
#df['host_is_superhost'] = df['host_is_superhost'].replace({'f': 0, 't': 1})

In [ ]:
# Convertir variables categóricas a numéricas
#df['host_is_superhost'] = df['host_is_superhost'].map({'f': 0, 't': 1})
#df['host_has_profile_pic'] = df['host_has_profile_pic'].map({'f': 0, 't': 1})
#df['host_identity_verified'] = df['host_identity_verified'].map({'f': 0, 't': 1})
#df['instant_bookable'] = df['instant_bookable'].map({'f': 0, 't': 1})

In [223]:
print(df['host_is_superhost'].head(10))

0    t
1    f
2    f
3    f
4    t
5    t
6    f
7    f
8    f
9    f
Name: host_is_superhost, dtype: object


In [224]:
# Declaramos las variables dependientes e independientes para la regresión logística
#Vars_Indep = df[['pclass', 'age', 'fare']]
#Var_Dep = df['alive']
Vars_Indep1= df[['price', 'accommodates']]
Var_Dep1= df['host_is_superhost']

# Caso 1
Vars_Indep2 = df[['price', 'accommodates']]
Var_Dep2 = df['host_is_superhost']

# Caso 2
Vars_Indep3 = df[['bedrooms', 'beds']]
Var_Dep3 = df['instant_bookable']

# Caso 3
Vars_Indep4 = df[['price', 'availability_90']]
Var_Dep4 = df['host_identity_verified']

# Caso 4
Vars_Indep5 = df[['minimum_nights', 'reviews_per_month']]
Var_Dep5 = df['host_is_superhost']

# Caso 5
Vars_Indep6 = df[['accommodates', 'bathrooms']]
Var_Dep6 = df['instant_bookable']

# Caso 6
Vars_Indep7 = df[['price', 'number_of_reviews']]
Var_Dep7 = df['host_identity_verified']

# Caso 7
Vars_Indep8 = df[['beds', 'availability_30']]
Var_Dep8 = df['host_is_superhost']

# Caso 8
Vars_Indep9 = df[['price', 'review_scores_rating']]
Var_Dep9 = df['instant_bookable']

# Caso 9
Vars_Indep10 = df[['reviews_per_month', 'bedrooms']]
Var_Dep10 = df['host_identity_verified']

In [225]:
# Redefinimos las variables
X = Vars_Indep1
y = Var_Dep1
x2 = Vars_Indep2
y2 = Var_Dep2           
x3 = Vars_Indep3
y3 = Var_Dep3
x4 = Vars_Indep4
y4 = Var_Dep4
x5 = Vars_Indep5
y5 = Var_Dep5
x6 = Vars_Indep6
y6 = Var_Dep6
x7 = Vars_Indep7
y7 = Var_Dep7
x8 = Vars_Indep8
y8 = Var_Dep8
x9 = Vars_Indep9
y9 = Var_Dep9
x10 = Vars_Indep10
y10 = Var_Dep10


In [226]:
# Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)



# Dividir cada conjunto de variables independientes y dependientes
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y, test_size=0.3, random_state=None)
X2_train, X2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.3, random_state=None)
X3_train, X3_test, y3_train, y3_test = train_test_split(x3, y3, test_size=0.3, random_state=None)
X4_train, X4_test, y4_train, y4_test = train_test_split(x4, y4, test_size=0.3, random_state=None)
X5_train, X5_test, y5_train, y5_test = train_test_split(x5, y5, test_size=0.3, random_state=None)
X6_train, X6_test, y6_train, y6_test = train_test_split(x6, y6, test_size=0.3, random_state=None)
X7_train, X7_test, y7_train, y7_test = train_test_split(x7, y7, test_size=0.3, random_state=None)
X8_train, X8_test, y8_train, y8_test = train_test_split(x8, y8, test_size=0.3, random_state=None)
X9_train, X9_test, y9_train, y9_test = train_test_split(x9, y9, test_size=0.3, random_state=None)
X10_train, X10_test, y10_train, y10_test = train_test_split(x10, y10, test_size=0.3, random_state=None)

In [227]:
#se escalan todos los datos
escalar = StandardScaler()

In [228]:
# Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos
#X_train = escalar.fit_transform(X_train)
#X_test = escalar.transform(X_test)

# Escalamos cada conjunto de datos (X_train y X_test) para las 10 variables
# --- Conjunto 1 ---
X1_train = escalar.fit_transform(X1_train)  
X1_test = escalar.transform(X1_test)       

# --- Conjunto 2 ---
X2_train = escalar.fit_transform(X2_train)
X2_test = escalar.transform(X2_test)

# --- Conjunto 3 ---
X3_train = escalar.fit_transform(X3_train)
X3_test = escalar.transform(X3_test)

# --- Conjunto 4 ---
X4_train = escalar.fit_transform(X4_train)
X4_test = escalar.transform(X4_test)

# --- Conjunto 5 ---
X5_train = escalar.fit_transform(X5_train)
X5_test = escalar.transform(X5_test)

# --- Conjunto 6 ---
X6_train = escalar.fit_transform(X6_train)
X6_test = escalar.transform(X6_test)

# --- Conjunto 7 ---
X7_train = escalar.fit_transform(X7_train)
X7_test = escalar.transform(X7_test)

# --- Conjunto 8 ---
X8_train = escalar.fit_transform(X8_train)
X8_test = escalar.transform(X8_test)

# --- Conjunto 9 ---
X9_train = escalar.fit_transform(X9_train)
X9_test = escalar.transform(X9_test)

# --- Conjunto 10 ---
X10_train = escalar.fit_transform(X10_train)
X10_test = escalar.transform(X10_test)

In [229]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()    

In [230]:
#entremanos el modelo   
#algoritmo.fit(X_train, y_train) 

# Entrenamos los 10 modelos uno por uno:

# Modelo 1
algoritmo.fit(X1_train, y1_train)

# Modelo 2
algoritmo.fit(X2_train, y2_train)

# Modelo 3
algoritmo.fit(X3_train, y3_train)

# Modelo 4
algoritmo.fit(X4_train, y4_train)

# Modelo 5
algoritmo.fit(X5_train, y5_train)

# Modelo 6
algoritmo.fit(X6_train, y6_train)

# Modelo 7
algoritmo.fit(X7_train, y7_train)

# Modelo 8
algoritmo.fit(X8_train, y8_train)

# Modelo 9
algoritmo.fit(X9_train, y9_train)

# Modelo 10
algoritmo.fit(X10_train, y10_train)

LogisticRegression()

In [231]:
print("Dimensiones del conjunto de entrenamiento:", X1_train.shape)
print("Dimensiones de X1_test:", X1_test.shape)
print("Dimensiones de X2_test:", X2_test.shape)
# Repite para los demás conjuntos de prueba

Dimensiones del conjunto de entrenamiento: (2761, 2)
Dimensiones de X1_test: (1184, 2)
Dimensiones de X2_test: (1184, 2)


In [112]:
# Selecciona las primeras 2 columnas de cada conjunto de prueba
#X1_test = X1_test[:, :2]
#X2_test = X2_test[:, :2]
#X3_test = X3_test[:, :2]
#X4_test = X4_test[:, :2]
#X5_test = X5_test[:, :2]
#X6_test = X6_test[:, :2]
#X7_test = X7_test[:, :2]
#X8_test = X8_test[:, :2]
#X9_test = X9_test[:, :2]
#X10_test = X10_test[:, :2]

In [232]:
#realizamos una predicción  
#y_pred = algoritmo.predict(X_test)
#y_pred


# Predicción Modelo 1
y1_pred = algoritmo.predict(X1_test)

# Predicción Modelo 2
y2_pred = algoritmo.predict(X2_test)

# Predicción Modelo 3
y3_pred = algoritmo.predict(X3_test)

# Predicción Modelo 4
y4_pred = algoritmo.predict(X4_test)

# Predicción Modelo 5
y5_pred = algoritmo.predict(X5_test)

# Predicción Modelo 6
y6_pred = algoritmo.predict(X6_test)

# Predicción Modelo 7
y7_pred = algoritmo.predict(X7_test)

# Predicción Modelo 8
y8_pred = algoritmo.predict(X8_test)

# Predicción Modelo 9
y9_pred = algoritmo.predict(X9_test)

# Predicción Modelo 10
y10_pred = algoritmo.predict(X10_test)

# Imprimir las predicciones de cada modelo
print("Predicciones Modelo 1:", y1_pred)    
print("Predicciones Modelo 2:", y2_pred)
print("Predicciones Modelo 3:", y3_pred)
print("Predicciones Modelo 4:", y4_pred)
print("Predicciones Modelo 5:", y5_pred)
print("Predicciones Modelo 6:", y6_pred)
print("Predicciones Modelo 7:", y7_pred)
print("Predicciones Modelo 8:", y8_pred)
print("Predicciones Modelo 9:", y9_pred)
print("Predicciones Modelo 10:", y10_pred)


Predicciones Modelo 1: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 2: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 3: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 4: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 5: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 6: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 7: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 8: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 9: ['t' 't' 't' ... 't' 't' 't']
Predicciones Modelo 10: ['t' 't' 't' ... 't' 't' 't']


In [ ]:

# Convierte las etiquetas reales a números
#y1_test = [0 if label == 'f' else 1 for label in y1_test]
#y2_test = [0 if label == 'f' else 1 for label in y2_test]
#y3_test = [0 if label == 'f' else 1 for label in y3_test]
#y4_test = [0 if label == 'f' else 1 for label in y4_test]
##y5_test = [0 if label == 'f' else 1 for label in y5_test]
#y6_test = [0 if label == 'f' else 1 for label in y6_test]
#y7_test = [0 if label == 'f' else 1 for label in y7_test]
#y8_test = [0 if label == 'f' else 1 for label in y8_test]
#y9_test = [0 if label == 'f' else 1 for label in y9_test]
#y10_test = [0 if label == 'f' else 1 for label in y10_test]


In [233]:
print("Etiquetas reales (y1_test):", y1_test[:10])
print("Etiquetas predichas (y1_pred):", y1_pred[:10])

Etiquetas reales (y1_test): 2181    t
2874    f
1223    f
1852    f
1696    f
1067    t
487     f
2270    f
296     f
1206    t
Name: host_is_superhost, dtype: object
Etiquetas predichas (y1_pred): ['t' 't' 't' 't' 't' 't' 't' 't' 't' 't']


In [234]:
#verifico la matriz de confusión
from sklearn.metrics import confusion_matrix
#matriz = confusion_matrix(y_test, y_pred)
#print('Matriz de Confusión:')
#print(matriz)


#from sklearn.metrics import confusion_matrix

# Matriz de confusión para cada modelo:

# --- Modelo 1 ---
matriz1 = confusion_matrix(y1_test, y1_pred)
print('\nMatriz de Confusión Modelo 1:')
print(matriz1)

# --- Modelo 2 ---
matriz2 = confusion_matrix(y2_test, y2_pred)
print('\nMatriz de Confusión Modelo 2:')
print(matriz2)

# --- Modelo 3 ---
matriz3 = confusion_matrix(y3_test, y3_pred)
print('\nMatriz de Confusión Modelo 3:')
print(matriz3)

# --- Modelo 4 ---
matriz4 = confusion_matrix(y4_test, y4_pred)
print('\nMatriz de Confusión Modelo 4:')
print(matriz4)

# --- Modelo 5 ---
matriz5 = confusion_matrix(y5_test, y5_pred)
print('\nMatriz de Confusión Modelo 5:')
print(matriz5)

# --- Modelo 6 ---
matriz6 = confusion_matrix(y6_test, y6_pred)
print('\nMatriz de Confusión Modelo 6:')
print(matriz6)

# --- Modelo 7 ---
matriz7 = confusion_matrix(y7_test, y7_pred)
print('\nMatriz de Confusión Modelo 7:')
print(matriz7)

# --- Modelo 8 ---
matriz8 = confusion_matrix(y8_test, y8_pred)
print('\nMatriz de Confusión Modelo 8:')
print(matriz8)

# --- Modelo 9 ---
matriz9 = confusion_matrix(y9_test, y9_pred)
print('\nMatriz de Confusión Modelo 9:')
print(matriz9)

# --- Modelo 10 ---
matriz10 = confusion_matrix(y10_test, y10_pred)
print('\nMatriz de Confusión Modelo 10:')
print(matriz10)


Matriz de Confusión Modelo 1:
[[  0 936]
 [  0 248]]

Matriz de Confusión Modelo 2:
[[  0 923]
 [  0 261]]

Matriz de Confusión Modelo 3:
[[  0 480]
 [  0 704]]

Matriz de Confusión Modelo 4:
[[   0   39]
 [   0 1145]]

Matriz de Confusión Modelo 5:
[[  0 929]
 [  0 255]]

Matriz de Confusión Modelo 6:
[[  0 480]
 [  0 704]]

Matriz de Confusión Modelo 7:
[[   0   28]
 [   0 1156]]

Matriz de Confusión Modelo 8:
[[  0 927]
 [  0 257]]

Matriz de Confusión Modelo 9:
[[  0 503]
 [  0 681]]

Matriz de Confusión Modelo 10:
[[   0   22]
 [   0 1162]]


In [248]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Configura el modelo con balanceo de clases y ajuste de umbral
modelo = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

# Lista de tus pares (X_train, X_test, y_train, y_test) para los 10 modelos
datos_modelos = [
    (X1_train, X1_test, y1_train, y1_test),
    (X2_train, X2_test, y2_train, y2_test),
    (X3_train, X3_test, y3_train, y3_test),
    (X4_train, X4_test, y4_train, y4_test),
    (X5_train, X5_test, y5_train, y5_test),
    (X6_train, X6_test, y6_train, y6_test),
    (X7_train, X7_test, y7_train, y7_test),
    (X8_train, X8_test, y8_train, y8_test),
    (X9_train, X9_test, y9_train, y9_test),
    (X10_train, X10_test, y10_train, y10_test)
]

# Corregir las matrices de confusión para cada modelo
for i, (X_train, X_test, y_train, y_test) in enumerate(datos_modelos, start=1):
    # Entrenar el modelo
    modelo.fit(X_train, y_train)
    
    # Predecir probabilidades y ajustar el umbral (ej. 0.3 para priorizar 'f')
    y_pred_prob = modelo.predict_proba(X_test)[:, 1]  # Probabilidad de 'f'
    y_pred_ajustado = ['f' if prob >= 0.3 else 't' for prob in y_pred_prob]  # Umbral ajustable
    
    # Matriz de confusión corregida
    matriz = confusion_matrix(y_test, y_pred_ajustado)
    
    print(f"\n--- Matriz de Confusión Modelo {i} (Umbral=0.3) ---")
    print(matriz)


--- Matriz de Confusión Modelo 1 (Umbral=0.3) ---
[[845  91]
 [244   4]]

--- Matriz de Confusión Modelo 2 (Umbral=0.3) ---
[[817 106]
 [248  13]]

--- Matriz de Confusión Modelo 3 (Umbral=0.3) ---
[[480   0]
 [704   0]]

--- Matriz de Confusión Modelo 4 (Umbral=0.3) ---
[[  38    1]
 [1142    3]]

--- Matriz de Confusión Modelo 5 (Umbral=0.3) ---
[[864  65]
 [250   5]]

--- Matriz de Confusión Modelo 6 (Umbral=0.3) ---
[[480   0]
 [704   0]]

--- Matriz de Confusión Modelo 7 (Umbral=0.3) ---
[[  25    3]
 [1154    2]]

--- Matriz de Confusión Modelo 8 (Umbral=0.3) ---
[[865  62]
 [246  11]]

--- Matriz de Confusión Modelo 9 (Umbral=0.3) ---
[[503   0]
 [681   0]]

--- Matriz de Confusión Modelo 10 (Umbral=0.3) ---
[[  22    0]
 [1162    0]]


In [235]:
from sklearn.metrics import precision_score

# Precisión para cada modelo (clasificación binaria con etiquetas 't' y 'f'):

# --- Modelo 1 ---
precision1 = precision_score(y1_test, y1_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 1:', precision1)

# --- Modelo 2 ---
precision2 = precision_score(y2_test, y2_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 2:', precision2)

# --- Modelo 3 ---
precision3 = precision_score(y3_test, y3_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 3:', precision3)

# --- Modelo 4 ---
precision4 = precision_score(y4_test, y4_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 4:', precision4)

# --- Modelo 5 ---
precision5 = precision_score(y5_test, y5_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 5:', precision5)

# --- Modelo 6 ---
precision6 = precision_score(y6_test, y6_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 6:', precision6)

# --- Modelo 7 ---
precision7 = precision_score(y7_test, y7_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 7:', precision7)

# --- Modelo 8 ---
precision8 = precision_score(y8_test, y8_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 8:', precision8)

# --- Modelo 9 ---
precision9 = precision_score(y9_test, y9_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 9:', precision9)

# --- Modelo 10 ---
precision10 = precision_score(y10_test, y10_pred, average='binary', pos_label='t')
print('\nPrecisión Modelo 10:', precision10)


Precisión Modelo 1: 0.20945945945945946

Precisión Modelo 2: 0.2204391891891892

Precisión Modelo 3: 0.5945945945945946

Precisión Modelo 4: 0.9670608108108109

Precisión Modelo 5: 0.21537162162162163

Precisión Modelo 6: 0.5945945945945946

Precisión Modelo 7: 0.9763513513513513

Precisión Modelo 8: 0.2170608108108108

Precisión Modelo 9: 0.575168918918919

Precisión Modelo 10: 0.981418918918919


In [236]:
# Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

#exactitud = accuracy_score(y_test, y_pred)
#print('Exactitud del modelo:')
#print(exactitud)


#from sklearn.metrics import accuracy_score

# Calculamos la exactitud para cada modelo:

# --- Modelo 1 ---
exactitud1 = accuracy_score(y1_test, y1_pred)
print('\nExactitud Modelo 1:', exactitud1)

# --- Modelo 2 ---
exactitud2 = accuracy_score(y2_test, y2_pred)
print('\nExactitud Modelo 2:', exactitud2)

# --- Modelo 3 ---
exactitud3 = accuracy_score(y3_test, y3_pred)
print('\nExactitud Modelo 3:', exactitud3)

# --- Modelo 4 ---
exactitud4 = accuracy_score(y4_test, y4_pred)
print('\nExactitud Modelo 4:', exactitud4)

# --- Modelo 5 ---
exactitud5 = accuracy_score(y5_test, y5_pred)
print('\nExactitud Modelo 5:', exactitud5)

# --- Modelo 6 ---
exactitud6 = accuracy_score(y6_test, y6_pred)
print('\nExactitud Modelo 6:', exactitud6)

# --- Modelo 7 ---
exactitud7 = accuracy_score(y7_test, y7_pred)
print('\nExactitud Modelo 7:', exactitud7)

# --- Modelo 8 ---
exactitud8 = accuracy_score(y8_test, y8_pred)
print('\nExactitud Modelo 8:', exactitud8)

# --- Modelo 9 ---
exactitud9 = accuracy_score(y9_test, y9_pred)
print('\nExactitud Modelo 9:', exactitud9)

# --- Modelo 10 ---
exactitud10 = accuracy_score(y10_test, y10_pred)
print('\nExactitud Modelo 10:', exactitud10)


Exactitud Modelo 1: 0.20945945945945946

Exactitud Modelo 2: 0.2204391891891892

Exactitud Modelo 3: 0.5945945945945946

Exactitud Modelo 4: 0.9670608108108109

Exactitud Modelo 5: 0.21537162162162163

Exactitud Modelo 6: 0.5945945945945946

Exactitud Modelo 7: 0.9763513513513513

Exactitud Modelo 8: 0.2170608108108108

Exactitud Modelo 9: 0.575168918918919

Exactitud Modelo 10: 0.981418918918919


In [237]:
# Verificar la distribución de clases en y_test y y_pred
from collections import Counter

print("Distribución en y1_test:", Counter(y1_test))
print("Distribución en y1_pred:", Counter(y1_pred))

Distribución en y1_test: Counter({'f': 936, 't': 248})
Distribución en y1_pred: Counter({'t': 1184})


In [238]:
from sklearn.linear_model import LogisticRegression
from collections import Counter
from sklearn.metrics import recall_score

# Definir el modelo con balanceo de clases (para manejar desequilibrio)
modelo = LogisticRegression(class_weight='balanced', random_state=42)

# Entrenar el modelo con tus datos del Modelo 1
modelo.fit(X1_train, y1_train)

# Obtener probabilidades para la clase 'f' (asumiento que es la clase minoritaria)
y1_pred_prob = modelo.predict_proba(X1_test)[:, 1]  # Probabilidades de la clase 'f'

# Ajustar el umbral de decisión (empieza con 0.3 y ajusta según necesidad)
umbral = 0.3  # Puedes probar con 0.4, 0.2, etc.
y1_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y1_pred_prob]

# Verificar distribución de predicciones
print("\nDistribución en y1_test (real):", Counter(y1_test))
print("Distribución en y1_pred_ajustado:", Counter(y1_pred_ajustado))

# Calcular métricas
sensibilidad1_ajustada = recall_score(y1_test, y1_pred_ajustado, pos_label='f')
print("\nSensibilidad ajustada (Recall para 'f'):", sensibilidad1_ajustada)


Distribución en y1_test (real): Counter({'f': 936, 't': 248})
Distribución en y1_pred_ajustado: Counter({'f': 1089, 't': 95})

Sensibilidad ajustada (Recall para 'f'): 0.9027777777777778


In [241]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score

# Modelo con balanceo de clases
modelo = LogisticRegression(class_weight='balanced', random_state=42)
modelo.fit(X1_train, y1_train)

# Predicciones con umbral ajustado
y1_pred_prob = modelo.predict_proba(X1_test)[:, 1]  # Probabilidad de 'f'
umbral = 0.3  # Ajusta según necesidad
y1_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y1_pred_prob]

# Sensibilidad corregida
sensibilidad = recall_score(y1_test, y1_pred_ajustado, pos_label='f')
print("Sensibilidad ajustada:", sensibilidad)

Sensibilidad ajustada: 0.9027777777777778


In [247]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
from collections import Counter

# Listas de datos de entrenamiento y prueba para cada modelo
X_train_list = [X1_train, X2_train, X3_train, X4_train, X5_train, X6_train, X7_train, X8_train, X9_train, X10_train]
y_train_list = [y1_train, y2_train, y3_train, y4_train, y5_train, y6_train, y7_train, y8_train, y9_train, y10_train]
X_test_list = [X1_test, X2_test, X3_test, X4_test, X5_test, X6_test, X7_test, X8_test, X9_test, X10_test]
y_test_list = [y1_test, y2_test, y3_test, y4_test, y5_test, y6_test, y7_test, y8_test, y9_test, y10_test]

# Umbral ajustado
umbral = 0.3

# Iterar sobre los modelos
for i, (X_train, y_train, X_test, y_test) in enumerate(zip(X_train_list, y_train_list, X_test_list, y_test_list), start=1):
    # Crear y entrenar el modelo
    modelo = LogisticRegression(class_weight='balanced', random_state=42)
    modelo.fit(X_train, y_train)
    
    # Predicciones con umbral ajustado
    y_pred_prob = modelo.predict_proba(X_test)[:, 1]  # Probabilidad de 'f'
    y_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y_pred_prob]
    
  
    
    # Calcular sensibilidad
    sensibilidad = recall_score(y_test, y_pred_ajustado, pos_label='f')
    print(f"Sensibilidad Modelo {i}:", sensibilidad)

Sensibilidad Modelo 1: 0.9027777777777778
Sensibilidad Modelo 2: 0.8851570964247021
Sensibilidad Modelo 3: 1.0
Sensibilidad Modelo 4: 0.9743589743589743
Sensibilidad Modelo 5: 0.930032292787944
Sensibilidad Modelo 6: 1.0
Sensibilidad Modelo 7: 0.8928571428571429
Sensibilidad Modelo 8: 0.9331175836030206
Sensibilidad Modelo 9: 1.0
Sensibilidad Modelo 10: 1.0


In [250]:
#calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

#sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="no")
#print('Sensibilidad del modelo:')
#print(sensibilidad)


#from sklearn.metrics import recall_score

# Sensibilidad para cada modelo (versión para clasificación binaria):
# Asumiendo que 'no' es tu etiqueta positiva para sensibilidad

# --- Modelo 1 ---
sensibilidad1 = recall_score(y1_test, y1_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 1 (Recall para clase "f"):', sensibilidad1)

# --- Modelo 2 ---
sensibilidad2 = recall_score(y2_test, y2_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 2 (Recall para clase "f"):', sensibilidad2)

# --- Modelo 3 ---
sensibilidad3 = recall_score(y3_test, y3_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 3 (Recall para clase "f"):', sensibilidad3)

# --- Modelo 4 ---
sensibilidad4 = recall_score(y4_test, y4_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 4 (Recall para clase "f"):', sensibilidad4)

# --- Modelo 5 ---
sensibilidad5 = recall_score(y5_test, y5_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 5 (Recall para clase "f"):', sensibilidad5)

# --- Modelo 6 ---
sensibilidad6 = recall_score(y6_test, y6_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 6 (Recall para clase "f"):', sensibilidad6)

# --- Modelo 7 ---
sensibilidad7 = recall_score(y7_test, y7_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 7 (Recall para clase "f"):', sensibilidad7)

# --- Modelo 8 ---
sensibilidad8 = recall_score(y8_test, y8_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 8 (Recall para clase "f"):', sensibilidad8)

# --- Modelo 9 ---
sensibilidad9 = recall_score(y9_test, y9_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 9 (Recall para clase "f"):', sensibilidad9)

# --- Modelo 10 ---
sensibilidad10 = recall_score(y10_test, y10_pred, average='binary', pos_label='f')
print('\nSensibilidad Modelo 10 (Recall para clase "f"):', sensibilidad10)


Sensibilidad Modelo 1 (Recall para clase "f"): 0.0

Sensibilidad Modelo 2 (Recall para clase "f"): 0.0

Sensibilidad Modelo 3 (Recall para clase "f"): 0.0

Sensibilidad Modelo 4 (Recall para clase "f"): 0.0

Sensibilidad Modelo 5 (Recall para clase "f"): 0.0

Sensibilidad Modelo 6 (Recall para clase "f"): 0.0

Sensibilidad Modelo 7 (Recall para clase "f"): 0.0

Sensibilidad Modelo 8 (Recall para clase "f"): 0.0

Sensibilidad Modelo 9 (Recall para clase "f"): 0.0

Sensibilidad Modelo 10 (Recall para clase "f"): 0.0


**reemplazar los valores**

In [240]:
#verificar los valores sin repetir
#unico=np.unique(df['class'])
#unico

# Verificar los valores únicos en las variables dependientes definidas
variables_dependientes = [Var_Dep1, Var_Dep2, Var_Dep3, Var_Dep4, Var_Dep5, Var_Dep6, Var_Dep7, Var_Dep8, Var_Dep9, Var_Dep10]

for i, var_dep in enumerate(variables_dependientes, start=1):
    unico = np.unique(var_dep)
    print(f"Valores únicos en Var_Dep{i}: {unico}")

Valores únicos en Var_Dep1: ['f' 't']
Valores únicos en Var_Dep2: ['f' 't']
Valores únicos en Var_Dep3: ['f' 't']
Valores únicos en Var_Dep4: ['f' 't']
Valores únicos en Var_Dep5: ['f' 't']
Valores únicos en Var_Dep6: ['f' 't']
Valores únicos en Var_Dep7: ['f' 't']
Valores únicos en Var_Dep8: ['f' 't']
Valores únicos en Var_Dep9: ['f' 't']
Valores únicos en Var_Dep10: ['f' 't']
